Repository Project-IS12/IS12-Warfare, pull requests merged in 2020-10, with the labels that each got.

#29 Armaggedon belt
  maps/oldfare/jobs/blue/blue_soldiers.dm
  maps/oldfare/jobs/red/red_soldiers.dm
  maps/oldfare/warfare_items.dm
Labels: feature

#34 Holomed Sign Fix
  code/game/objects/structures/signs.dm
  maps/oldfare/warfare-2.dmm
Labels: fix

#35 Astrafare and related code changes
  code/game/gamemodes/warfare/structures.dm
  code/game/turfs/flooring/flooring_premade.dm
  icons/obj/warfare.dmi
  maps/astrafare/warfare-1.dmm
  maps/astrafare/warfare-2.dmm
  maps/astrafare/warfare-3.dmm
  maps/astrafare/warfare_define.dm
Labels: enhancement, feature

#37 Astrafare map changes to match Warfare Classic paradigm.
  code/game/gamemodes/warfare/turfs.dm
  maps/astrafare/warfare-1.dmm
  maps/astrafare/warfare-2.dmm
Labels: enhancement

#42 Added Caps Into The Code
  icons/mob/onmob/head.dmi
  icons/obj/clothing/hats.dmi
  maps/oldfare/warfare_items.dm
Labels: sprites
